### ISSUE TITLE
Anchovy CSS preprocessor consumes essential whitespaces in media queries

### ISSUE THREAD

**Issue by pydsigner** [pydsigner/anchovy#23]
### Description:

Any media query with a declaration as an immediate child will have all the whitespace within the declaration removed, leading to problems when more then one value is supplied to the declaration. tinycss will supply a comment to force compliance, but minifiers may strip these out.

### Minimal Input:
```css
@media (max-width: 700px) {
    test: 1 2;
}
```

### Expected:
```css
@media (max-width: 700px) {
    test: 1 2;
}
```

### Actual:
```css
@media (max-width: 700px) {
test:1/**/2;}
```
