### ISSUE TITLE
Anchovy CSS processor produces empty rules

### ISSUE THREAD

**Issue by pydsigner** [pydsigner/anchovy#24]
### Description:

Any qualified rule whose only children are other qualified rules or at rules will be present as an empty rule in the final output. This is not strictly harmful but is undesirable.

### Minimal Input:
```css
.cls {
    @media (max-width: 700px) {
        test: 1;
    }
}
```
```css
a {
    b {
        padding: 0;
    }
}
```

### Expected:
```css
@media (max-width: 700px) {
    .cls {
        test:1;
    }
}
```
```css
a b {
    padding: 0;
}
```

### Actual:
```css
.cls {
}
@media (max-width: 700px) {
.cls {
test:1;
}
}
```
```css
a {
}
a b {
padding: 0;
}
```
